version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
      - image: postgres:9.6
    working_directory: ~/redash
    steps:
      - checkout
      - run: sudo apt install python-pip python-dev -y
      - run: sudo pip install --upgrade setuptools
      - run: sudo pip install -r requirements_dev.txt
      - run: sudo pip install -r requirements.txt
      - run: make deps
      - run:
          name: test
          command: nosetests --with-xunit --xunit-file=/tmp/junit/junit.xml --with-coverage --cover-package=redash tests/
          no_output_timetou: "30m"
