version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
      - image: postgres:9.6
      - image: redis:3
    working_directory: ~/redash
    steps:
      - checkout
      - run: sudo apt install python-pip python-dev -y
      - run: sudo pip install --upgrade setuptools
      - run: sudo pip install -r requirements_dev.txt
      - run: sudo pip install -r requirements.txt
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-redash-npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-redash-npm-cache-{{ .Branch }}-
            - v1-redash-npm-cache-
      - run: make deps
      - save_cache:
          name: Save node_modules cache
          key: - v1-redash-npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules/
      - run:
          name: test
          command: nosetests --with-xunit --xunit-file=/tmp/junit/junit.xml --with-coverage --cover-package=redash tests/
          no_output_timetou: "30m"
